### ISSUE TITLE
Don't have your home directory in the source code

### ISSUE THREAD

**Issue by wpm** [jkahn/samyro#6]
`cli/shared.py:set_shared_args` specifies `/home/jeremy/notebooks/shakespeare/shakespeare` as the default argument for `--checkpoint_pattern`. A better choice would be the current directory.

I stumbled across this when I forgot to put an `@` in front of the name of a command line file, causing this default to be used.

`learn.py` and `sample.py` also specify `/opt/data/texts/shakespeare_input.txt` as default arguments. This doesn't seem as bad to me because that's a reasonable place to put data. If I hit that error I would understand the convention you were trying to suggest.

**Comment by jkahn** [comment]
homedir removed. path to data directories left as-is.
